import { Logger } from '@nestjs/common';
import { Prisma, PrismaClient } from '@prisma/client';
import { TenantContextService } from '../context/tenant-context.service';
import { ERROR_CODE } from '../constants/error-codes.constant';
import { ForbiddenAppException } from '../exceptions/app.exception';
import {
  DATA_SCOPED_OPERATIONS,
  WHERE_SCOPED_OPERATIONS,
  isTenantScopedModel,
  tenantFieldFor,
} from './tenant-scope';

export const TENANT_PRISMA = Symbol('TENANT_PRISMA');

const logger = new Logger('TenantPrisma');

type QueryArgs = Record<string, unknown> & {
  where?: Record<string, unknown>;
  data?: Record<string, unknown> | Record<string, unknown>[];
  create?: Record<string, unknown>;
  update?: Record<string, unknown>;
};

function assertNoForeignTenant(field: string, value: unknown, companyId: string): void {
  if (value !== undefined && value !== null && value !== companyId) {
    logger.warn(`Blocked cross-tenant query: ${field}=${String(value)} while acting as ${companyId}`);
    throw new ForbiddenAppException(
      'لا يمكن الوصول إلى بيانات شركة أخرى',
      ERROR_CODE.CROSS_TENANT_ACCESS,
    );
  }
}

function scopeWhere(args: QueryArgs, field: string, companyId: string): QueryArgs {
  const where = (args.where ?? {}) as Record<string, unknown>;
  assertNoForeignTenant(field, where[field], companyId);
  return { ...args, where: { ...where, [field]: companyId } };
}

function scopeData(
  data: Record<string, unknown>,
  field: string,
  companyId: string,
): Record<string, unknown> {
  // `Company.id` is generated by the database on create; only foreign-key columns are injected.
  if (field === 'id') {
    return data;
  }
  assertNoForeignTenant(field, data[field], companyId);
  return { ...data, [field]: companyId };
}

/**
 * Wraps the Prisma client so that every query is narrowed to the company of the
 * current request. This is the second of three isolation layers (JWT claim →
 * query extension → company-scoped unique constraints): even a service that
 * forgets its `companyId` filter cannot read or write another tenant's rows.
 */
export function extendWithTenantScope(client: PrismaClient, context: TenantContextService) {
  return client.$extends({
    name: 'tenant-scope',
    query: {
      $allModels: {
        async $allOperations({ model, operation, args, query }) {
          const companyId = context.getCompanyId();

          if (!companyId || !isTenantScopedModel(model)) {
            return query(args);
          }

          const field = tenantFieldFor(model);
          let scopedArgs = args as QueryArgs;

          if (WHERE_SCOPED_OPERATIONS.has(operation)) {
            scopedArgs = scopeWhere(scopedArgs, field, companyId);
          }

          if (DATA_SCOPED_OPERATIONS.has(operation)) {
            if (operation === 'upsert') {
              scopedArgs = scopeWhere(scopedArgs, field, companyId);
              if (scopedArgs.create) {
                scopedArgs = {
                  ...scopedArgs,
                  create: scopeData(scopedArgs.create, field, companyId),
                };
              }
            } else if (Array.isArray(scopedArgs.data)) {
              scopedArgs = {
                ...scopedArgs,
                data: scopedArgs.data.map((row) => scopeData(row, field, companyId)),
              };
            } else if (scopedArgs.data) {
              scopedArgs = { ...scopedArgs, data: scopeData(scopedArgs.data, field, companyId) };
            }
          }

          return query(scopedArgs as Prisma.Args<unknown, never>);
        },
      },
    },
  });
}

export type TenantPrismaClient = ReturnType<typeof extendWithTenantScope>;
