/**
 * Stable, machine-readable error codes returned in every failed API response.
 * The frontend maps these to UI behaviour; the Arabic message is for display only.
 */
export const ERROR_CODE = {
  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',

  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  EMAIL_ALREADY_USED: 'EMAIL_ALREADY_USED',

  // Authorization / tenancy
  FORBIDDEN: 'FORBIDDEN',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  CROSS_TENANT_ACCESS: 'CROSS_TENANT_ACCESS',
  TENANT_CONTEXT_MISSING: 'TENANT_CONTEXT_MISSING',

  // Company
  COMPANY_SLUG_TAKEN: 'COMPANY_SLUG_TAKEN',
  COMPANY_SUSPENDED: 'COMPANY_SUSPENDED',

  // Roles
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  SYSTEM_ROLE_IMMUTABLE: 'SYSTEM_ROLE_IMMUTABLE',
  ROLE_IN_USE: 'ROLE_IN_USE',
  LAST_OWNER_PROTECTED: 'LAST_OWNER_PROTECTED',

  // Catalog / inventory (used from Phase 2 onward)
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  SKU_ALREADY_USED: 'SKU_ALREADY_USED',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',

  // CRM / messaging (Phase 3)
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  CUSTOMER_PHONE_TAKEN: 'CUSTOMER_PHONE_TAKEN',
  CUSTOMER_BLOCKED: 'CUSTOMER_BLOCKED',
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  ASSIGNEE_INVALID: 'ASSIGNEE_INVALID',

  // Orders
  ORDER_CREATE_FAILED: 'ORDER_CREATE_FAILED',
  ORDER_INVALID_TRANSITION: 'ORDER_INVALID_TRANSITION',

  // Billing
  PLAN_LIMIT_REACHED: 'PLAN_LIMIT_REACHED',
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
